services:
  - type: web
    name: smartinfra-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 4000

  - type: web
    name: smartinfra-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
